# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Update Terraform documentation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-docs:
    name: Update Terraform documentation
    uses: canonical/operator-workflows/.github/workflows/generate_terraform_docs.yaml@main
    secrets: inherit
    with:
      terraform-directory: terraform,terraform/tests
