{
 "title": "Maubot Service Health",
 "tags": [ "service-health" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheusds", "query": "prometheus" },
   { "name": "maubot_model", "query": { "query": "label_values(juju_model)" } }
  ]
 },
 "panels": [
  {
   "title": "LATENCY",
   "type": "timeseries",
   "description": "Duration of requests by phase",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{juju_application=~\"maubot\",juju_model=~\"$maubot_model\",phase=~\"(connect|processing|resolve|tls|transfer)\",probe_target=~\"http://127\\\\.0\\\\.0\\\\.1:29316/_matrix/maubot/\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "description": "Number of requests with error status codes (below 200 or 400 and above)",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(probe_http_status_code{probe_target=\"http://127.0.0.1:29316/_matrix/maubot/\", juju_application=\"maubot\", juju_model=~\"$maubot_model\"} <= 199 OR probe_http_status_code{probe_target=\"http://127.0.0.1:29316/_matrix/maubot/\", juju_application=\"maubot\", juju_model=~\"$maubot_model\"} >= 400)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "description": "No traffic metric for this charm",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SATURATION",
   "type": "timeseries",
   "description": "Response time of the blackbox probe. Higher values indicate the target is responding more slowly.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{juju_application=\"maubot\",probe_target=\"http://127.0.0.1:29316/_matrix/maubot/\", juju_model=~\"$maubot_model\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}